# Generated by Django 2.2.5 on 2020-02-07 00:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('Śródmieście', 'Śródmieście'), ('Mokotów', 'Mokotów'), ('Ursynów', 'Ursynów'), ('Wola', 'Wola'), ('Bielany', 'Bielany'), ('Praga Północ', 'Praga Północ'), ('Praga Południe', 'Praga Południe')], max_length=50)),
                ('link', models.URLField(help_text='www.websiteurl.pl')),
                ('additionalInfo', models.CharField(blank=True, max_length=500, null=True)),
                ('is_updated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop24H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('Śródmieście', 'Śródmieście'), ('Mokotów', 'Mokotów'), ('Ursynów', 'Ursynów'), ('Wola', 'Wola'), ('Bielany', 'Bielany'), ('Praga Północ', 'Praga Północ'), ('Praga Południe', 'Praga Południe')], max_length=50)),
                ('link', models.URLField(help_text='www.websiteurl.pl')),
                ('week_day', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56)),
                ('additionalInfo', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('additionalInfo', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ManyToManyField(related_name='snack', to='restapi.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('additionalInfo', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ManyToManyField(related_name='shot', to='restapi.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('additionalInfo', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ManyToManyField(related_name='drink', to='restapi.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('additionalInfo', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ManyToManyField(related_name='beverage', to='restapi.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('additionalInfo', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ManyToManyField(related_name='beer', to='restapi.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
                ('open_hours', models.TimeField()),
                ('close_hours', models.TimeField()),
                ('place', models.ForeignKey(on_delete=True, related_name='openinghours', to='restapi.Place')),
            ],
            options={
                'unique_together': {('place', 'week_day')},
            },
        ),
    ]
