# Generated by Django 2.2.5 on 2020-02-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='place',
            field=models.OneToOneField(on_delete=True, primary_key=True, serialize=False, to='restapi.Place'),
        ),
    ]
