# Generated by Django 2.2.5 on 2020-01-02 16:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Shop24H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('Śródmieście', 'Śródmieście'), ('Mokotów', 'Mokotów'), ('Ursynów', 'Ursynów'), ('Wola', 'Wola'), ('Bielany', 'Bielany'), ('Praga Północ', 'Praga Północ'), ('Praga Południe', 'Praga Południe')], max_length=50)),
                ('link', models.URLField(help_text='www.websiteurl.pl')),
                ('week_day', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56)),
                ('additionalInfo', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='close_hours',
        ),
        migrations.RemoveField(
            model_name='place',
            name='open_hours',
        ),
        migrations.RemoveField(
            model_name='place',
            name='week_day',
        ),
        migrations.AddField(
            model_name='place',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
                ('open_hours', models.TimeField()),
                ('close_hours', models.TimeField()),
                ('place', models.ForeignKey(on_delete=True, related_name='openinghours', to='restapi.Place')),
            ],
            options={
                'unique_together': {('place', 'week_day')},
            },
        ),
    ]