# Generated by Django 2.2.5 on 2020-02-19 23:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_credits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['week_day']},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='shop24h',
            name='week_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=13),
        ),
    ]
