# Generated by Django 2.2.5 on 2020-02-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
