# Generated by Django 2.2.5 on 2020-02-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200220_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='beverage',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='shop24h',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='shot',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='snack',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
    ]
