# Generated by Django 2.2.5 on 2020-02-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_remove_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
