# Generated by Django 2.2.5 on 2020-02-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20200220_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='close_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='open_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
