# Generated by Django 2.2.5 on 2020-02-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
