# Generated by Django 2.2.5 on 2020-02-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_remove_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.TextField(default='Jazda', max_length=30),
        ),
    ]
