# Generated by Django 2.2.5 on 2020-02-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20200220_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openinghours', to='restapi.Place'),
        ),
    ]
