# Generated by Django 2.2.5 on 2020-02-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
